"""empty message

Revision ID: 119c9ba9f8ac
Revises: 
Create Date: 2020-09-01 04:00:43.778429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119c9ba9f8ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.bulk_insert(user_table,
        [{'id':1, 'username':'admin', 'password_hash':"pbkdf2:sha256:150000$bYfMPHwa$1a5de454f4056ddcdbb4fdf485040595abc195489e4191f94b9376f3dcbe2355"}]
    )
    op.create_table('htmls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('html_key', sa.String(length=64), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('htmls')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
